language: bash
dist: trusty
sudo: true
branches:
  only:
  - master
before_install: bash etc/ci-setup.sh
install: true
script: eval "$TEST_CMD"
after_script: heroku keys:remove $USER@`hostname`
env:
  global:
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  matrix:
  - TEST_CMD="sh etc/hatchet-test.sh spec/"
  - TEST_CMD="/tmp/testrunner/bin/run -c ."
