language: bash
sudo: true
branches:
  only:
  - master
before_install:
- curl --silent https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz | tar xz -C
  /tmp/
- git clone https://github.com/heroku/heroku-buildpack-testrunner.git /tmp/testrunner
- gem install heroku_hatchet -v 1.4.1
- gem install rspec -v 3.3.0
- gem install rspec-retry -v 0.4.2
- sh etc/hatchet_travis_setup.sh
install: true
script: eval $TEST_CMD
after_script: heroku keys:remove $USER@`hostname`
env:
  global:
  - HATCHET_RETRIES=3
  - HATCHET_DEPLOY_STRATEGY=git
  - HATCHET_BUILDPACK_BASE="https://github.com/heroku/heroku-buildpack-jvm-common.git"
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  - secure: V3C87flUuD4qPaOWReIE10UWGhAXQYKEsB8RFtBLr+zHWWWQYY6vCZVB8Eh0EwbWHxQ6TxjRdvqlznIcHWX1TrPjU6OoclBX8hZ6qDaPcd+1Z2VJp2FUTcjy7d9l2o1nGTCjexlGP+4959ymf/YuFgW3M9LvhKld80I9j5Sxlyo=
  matrix:
  - TEST_CMD="sh etc/hatchet-test.sh"
  - TEST_CMD="/tmp/testrunner/bin/run -c ."
